on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    
permissions:
  contents: read

jobs:
  call-workflow:
    uses: REX-SEMGREP-TEST/Workflow-Repo/.github/workflows/semgrep.yml@main
    secrets:
      token: ${{ secrets.SEMGREP_APP_TOKEN }}
